export const CyberpunkTheme = {
  colors: {
    background: "#0B1623",
    cardBackground: "#132236",
    cardBorder: "#1E3350",
    primary: "#E8587A",
    secondary: "#4ECDC4",
    accent: "#FFB347",
    text: "#F0F4F8",
    textSecondary: "#8BA4BE",
    textMuted: "#546B84",
    success: "#56D89B",
    error: "#FF6B7A",
    warning: "#FFD166",
    neonPink: "#E8587A",
    neonCyan: "#4ECDC4",
    neonPurple: "#A78BFA",
    glowPink: "rgba(232, 88, 122, 0.25)",
    glowCyan: "rgba(78, 205, 196, 0.25)",
    glowPurple: "rgba(167, 139, 250, 0.25)",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 6,
    md: 12,
    lg: 16,
    xl: 20,
  },
  shadows: {
    neonPink: {
      shadowColor: "#E8587A",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 4,
    },
    neonCyan: {
      shadowColor: "#4ECDC4",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 4,
    },
    neonPurple: {
      shadowColor: "#A78BFA",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 4,
    },
    cardGlow: {
      shadowColor: "#4ECDC4",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 2,
    },
  },
} as const;
